# RandomWOW configuration
RANDOMX_ARGON_MEMORY = 262144          # Number of 1 KiB Argon2 blocks in the Cache
RANDOMX_ARGON_ITERATIONS = 3           # Number of Argon2d iterations for Cache initialization
RANDOMX_ARGON_LANES = 1                # Number of parallel lanes for Cache initialization
RANDOMX_ARGON_SALT = "RandomWOW\x01"   # Argon2 salt
RANDOMX_CACHE_ACCESSES = 8             # Number of random Cache accesses per Dataset item
RANDOMX_SUPERSCALAR_LATENCY = 170      # Target latency for SuperscalarHash in CPU cycles
RANDOMX_DATASET_BASE_SIZE = 2147483648 # Dataset base size in bytes
RANDOMX_DATASET_EXTRA_SIZE = 33554368  # Dataset extra size in bytes
RANDOMX_PROGRAM_SIZE = 256             # Number of instructions in a RandomX program
RANDOMX_PROGRAM_ITERATIONS = 1024      # Number of iterations per program
RANDOMX_PROGRAM_COUNT = 16             # Number of programs per hash
RANDOMX_JUMP_BITS = 8                  # Jump condition mask size in bits
RANDOMX_JUMP_OFFSET = 8                # Jump condition mask offset in bits
RANDOMX_SCRATCHPAD_L3 = 1048576        # Scratchpad L3 size in bytes
RANDOMX_SCRATCHPAD_L2 = 131072         # Scratchpad L2 size in bytes
RANDOMX_SCRATCHPAD_L1 = 16384          # Scratchpad L1 size in bytes

# Instruction frequencies (per 256 opcodes)
# Total sum of frequencies must be 256
RANDOMX_FREQ_IADD_RS = 25
RANDOMX_FREQ_IADD_M = 7
RANDOMX_FREQ_ISUB_R = 16
RANDOMX_FREQ_ISUB_M = 7
RANDOMX_FREQ_IMUL_R = 16
RANDOMX_FREQ_IMUL_M = 4
RANDOMX_FREQ_IMULH_R = 4
RANDOMX_FREQ_IMULH_M = 1
RANDOMX_FREQ_ISMULH_R = 4
RANDOMX_FREQ_ISMULH_M = 1
RANDOMX_FREQ_IMUL_RCP = 8
RANDOMX_FREQ_INEG_R = 2
RANDOMX_FREQ_IXOR_R = 15
RANDOMX_FREQ_IXOR_M = 5
RANDOMX_FREQ_IROR_R = 10
RANDOMX_FREQ_IROL_R = 0
RANDOMX_FREQ_ISWAP_R = 4
RANDOMX_FREQ_FSWAP_R = 8
RANDOMX_FREQ_FADD_R = 20
RANDOMX_FREQ_FADD_M = 5
RANDOMX_FREQ_FSUB_R = 20
RANDOMX_FREQ_FSUB_M = 5
RANDOMX_FREQ_FSCAL_R = 6
RANDOMX_FREQ_FMUL_R = 20
RANDOMX_FREQ_FDIV_M = 4
RANDOMX_FREQ_FSQRT_R = 6
RANDOMX_FREQ_CBRANCH = 16
RANDOMX_FREQ_CFROUND = 1
RANDOMX_FREQ_ISTORE = 16
RANDOMX_FREQ_NOP = 0
