name: Build and Test on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Homebrew, Bun, WABT)
        run: |
          brew update
          brew install cmake llvm node binaryen wabt tcc
          # Add LLVM (clang, lld) to PATH
          echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> $GITHUB_ENV
          # Install Bun
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Patch Makefile to remove -mrelaxed-simd
        run: sed -i '' 's/-mrelaxed-simd//g' Makefile

      - name: Patch relaxed SIMD intrinsic in semifloat.c
        run: |
          sed -i '' 's/wasm_f64x2_relaxed_madd(wasm_f64x2_neg(c), b, a)/\
    wasm_f64x2_add(wasm_f64x2_mul(a, b), wasm_f64x2_neg(c))/g' \
            src/jit/stubs/semifloat.c

      - name: Install Node.js dependencies
        run: bun i --verbose

      - name: Build project (patched)
        run: |
          echo "Starting build on macOS..."
          bun scripts/build.ts
          echo "Build complete."

      - name: Run RandomX example (Single Thread)
        run: node examples/randomx_single.js

      - name: Patch randomx_threaded.js to stop after 10 intervals
        run: |
          echo "Limiting randomx_threaded.js to 10 hashrate prints..."
          sed -i '' '/let start_time = performance.now()/a\
    let intervalCount = 0;\
    const maxIntervals = 10;' examples/randomx_threaded.js
          sed -i '' '/setInterval(() => {/a\
    if (++intervalCount >= maxIntervals) process.exit(0);' \
            examples/randomx_threaded.js

      - name: Run RandomX example (Multi Thread)
        run: node examples/randomx_threaded.js

      - name: Run SuperScalarHash example
        run: node examples/superscalarhash.js

      - name: Test Summary
        run: echo "✅ All tests completed successfully on macOS with patched relaxed SIMD and controlled threaded output."
