name: Ubuntu Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies (APT, Bun, WABT)
        run: |
          echo "Installing core build tools..."
          sudo apt-get update
          sudo apt-get install -y build-essential clang lld cmake curl wget nodejs npm binaryen tcc

          echo "Installing WABT 1.0.33 from official binary release..."
          wget https://github.com/WebAssembly/wabt/releases/download/1.0.33/wabt-1.0.33-ubuntu.tar.gz
          tar -xzf wabt-1.0.33-ubuntu.tar.gz
          sudo cp wabt-1.0.33/bin/* /usr/local/bin/

          echo "Installing Bun..."
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          echo "$BUN_INSTALL/bin" >> $GITHUB_PATH

          echo "✅ Verifying key tools..."
          which wasm-objdump && wasm-objdump --version
          which wasm-opt && wasm-opt --version
          which wat2wasm && wat2wasm --version
          which clang && clang --version
          which bun && bun --version
          which node && node --version
          which tcc && tcc -v
          nproc

      - name: Install Node.js dependencies
        run: |
          echo "Installing project dependencies using bun..."
          bun i --verbose

      - name: Build project (no relaxed SIMD)
        run: |
          echo "Starting project build without -mrelaxed-simd..."
          bun scripts/build.ts
          echo "Build completed."

      - name: Run RandomX example (Single Thread)
        run: |
          echo "Running single-threaded RandomX test..."
          node examples/randomx_single.js

      - name: Run RandomX example (Multi Thread)
        run: |
          echo "Running multi-threaded RandomX test..."
          node examples/randomx_threaded.js

      - name: Run SuperScalarHash example
        run: |
          echo "Running SuperScalarHash test..."
          node examples/superscalarhash.js

      - name: Test Summary
        run: echo "✅ All tests completed successfully on Ubuntu (no relaxed SIMD)."
