name: Ubuntu Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies (APT, Bun, wabt via npm)
        run: |
          echo "Updating APT and installing core tools..."
          sudo apt-get update
          sudo apt-get install -y build-essential clang lld cmake curl wget nodejs npm binaryen tcc

          echo "Installing wabt via npm globally..."
          sudo npm install -g wabt

          echo "Installing Bun via official script..."
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          echo "$BUN_INSTALL/bin" >> $GITHUB_PATH

          echo "Verifying installations:"
          which wasm-objdump && wasm-objdump --version
          which wasm-opt && wasm-opt --version
          which wat2wasm && wat2wasm --version
          which clang && clang --version
          which node && node --version
          which bun && bun --version
          which tcc && tcc -v
          nproc

      - name: Install Node.js dependencies
        run: |
          echo "Installing project Node.js dependencies using bun..."
          bun i --verbose

      - name: Build project
        run: |
          echo "Starting project build..."
          bun scripts/build.ts
          echo "Build complete."

      - name: Run RandomX example (Single Thread)
        run: |
          node examples/randomx_single.js

      - name: Run RandomX example (Multi Thread)
        run: |
          node examples/randomx_threaded.js

      # Optional: Main example
      # - name: Run RandomX example (Main)
      #   run: node examples/randomx.js

      - name: Run SuperScalarHash example
        run: |
          node examples/superscalarhash.js

      - name: Test summary
        run: echo "✅ All Ubuntu tests completed successfully."
